exclude_paths:
  - 'tests/**'
  - 'docs/**'
ratings:
  paths:
    - 'accountable/**'
engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 60
